local i = require("styling").icons
local b = require("styling").borders.default

require("symbols-outline").setup({
    highlight_hovered_item = true,
    show_guides = true,
    auto_preview = false,
    position = "right",
    border = { b.tl, b.t, b.tr, b.r, b.br, b.b, b.bl, b.l },
    relative_width = true,
    width = 25,
    auto_close = false,
    show_numbers = false,
    show_relative_numbers = false,
    show_symbol_details = true,
    preview_bg_highlight = "Pmenu",
    autofold_depth = nil,
    auto_unfold_hover = true,
    fold_markers = { i.foldercl[1], i.folderop[1] },
    wrap = false,
    keymaps = {
        close = { "<Esc>", "q" },
        goto_location = "L",
        focus_location = "l",
        hover_symbol = "h",
        toggle_preview = "<M-p>",
        rename_symbol = "R",
        code_actions = "a",
        fold = "zc",
        unfold = "zo",
        fold_all = "zM",
        unfold_all = "zR",
        fold_reset = "za",
    },
    lsp_blacklist = {},
    symbol_blacklist = {},
    symbols = {
        Method = { icon = " ", hl = "@method" },
        Function = { icon = " ", hl = "@function" },
        Constructor = { icon = " ", hl = "@constructor" },
        Field = { icon = " ", hl = "@field" },
        Variable = { icon = " ", hl = "@variable" },
        Class = { icon = " ", hl = "@type" },
        Interface = { icon = " ", hl = "@type" },
        Module = { icon = " ", hl = "@include" },
        Namespace = { icon = " ", hl = "@namespace" },
        Package = { icon = " ", hl = "@include" },
        Property = { icon = " ", hl = "@method" },
        Enum = { icon = " ", hl = "@type" },
        Object = { icon = " ", hl = "@type" },
        Null = { icon = " ", hl = "@type" },
        Key = { icon = " ", hl = "@keyword" },
        File = { icon = " ", hl = "Directory" },
        EnumMember = { icon = " ", hl = "@field" },
        Constant = { icon = " ", hl = "@constant" },
        Array = { icon = " ", hl = "@constant" },
        Struct = { icon = " ", hl = "@type" },
        Event = { icon = " ", hl = "@type" },
        Operator = { icon = " ", hl = "@operator" },
        TypeParameter = { icon = " ", hl = "@parameter" },
        String = { icon = " ", hl = "@string" },
        Number = { icon = " ", hl = "@number" },
        Boolean = { icon = " ", hl = "@boolean" },
    },
})
