local p = require("config.themes." .. THEME .. ".palette")

local M = {}

M.editor = {
    Normal           = { fg = p.fg,       bg = p.bg                                          },
    NormalNC         = { fg = p.fg,       bg = p.bgDim                                      },
    NormalFloat      = { fg = p.fg, bg = p.bgDark },
    FloatBorder      = { fg = p.fill1, bg = p.bgDark },
    ColorColumn      = {                     bg = p.bgDim                                      },
    Cursor           = { reverse = true                                                         },
    lCursor          = { link = "Cursor" },
    CursorIM         = { link = "Cursor" },
    TermCursor       = { link = "Cursor" },
    TermCursorNC     = { link = "Cursor" },
    MatchParen       = { fg = p.violet,       bg = p.fill5, bold = true                     },
    NonText          = { fg = p.fill3,       bg = p.none                                           },
    Conceal          = { fg = p.none,        bg = p.none                                           },
    Whitespace       = { fg = p.fill3,       bg = p.none                                           },
    Pmenu            = { fg = p.fg,       bg = p.bgDark                                    },
    PmenuSel         = { fg = p.cyan,       bg = p.fill4                                          },
    PmenuSbar        = { fg = p.fg,       bg = p.fill1                                      },
    PmenuThumb       = { fg = p.cyan,       bg = p.fill3                                          },
    SpecialKey       = { fg = p.fill4,       bg = p.none                                           },
    SpellBad         = {                     bg = p.none,       underline = true, sp = p.red },
    SpellCap         = {                     bg = p.none,       underline = true, sp = p.yellow },
    SpellLocal       = {                     bg = p.none,       underline = true, sp = p.fg  },
    SpellRare        = {                     bg = p.none,       underline = true, sp = p.fgLight  },
    Visual           = { fg = p.none,        bg = p.fill4                                          },
    VisualNOS        = { fg = p.none,        bg = p.fill4                                          },
    Folded           = { fg = p.fill4,       bg = p.none                                           },
    FoldColumn       = { fg = p.fill4,       bg = p.none                                           },
    SignColumn       = { fg = p.fill2,       bg = p.none                                           },
    LineNrAbove      = { fg = p.fill4,       bg = p.none                                           },
    LineNr           = { fg = p.fg,       bg = p.none                                           },
    LineNrBelow      = { fg = p.fill4,       bg = p.none                                           },
    CursorLineNr     = { fg = p.fg,       bg = p.fill1                                      },
    CursorLine       = { fg = p.none,        bg = p.fill1                                      },
    CursorColumn     = { link = "CursorLine"                                                       },
    CursorLineSign   = { link = "SignColumn"                                                       },
    CursorLineFold   = { link = "FoldColumn"                                                       },
    Directory        = { fg = p.cyan,       bg = p.none                                           },
    EndOfBuffer      = { fg = p.fill2,       bg = p.none                                           },
    ErrorMsg         = { fg = p.fg,       bg = p.red                                         },
    ModeMsg          = { fg = p.fg,       bg = p.none,       bold = true                     },
    MoreMsg          = { fg = p.yellow,      bg = p.none                                           },
    MsgArea          = { link = "Normal"                                                           },
    WarningMsg       = { fg = p.yellow,      bg = p.bg,      reverse = true                  },
    MsgSeparator     = { fg = p.fg,       bg = p.fill1                                          },
    Question         = { fg = p.fg,       bg = p.none                                           },
    StatusLine       = { fg = p.fg,       bg = p.fill2                                          },
    StatusLineNC     = { fg = p.fgDim,       bg = p.fill2                                          },
    StatusLineTerm   = { link = "StatusLine" },
    StatusLineTermNC = { link = "StatusLineNC" },
    WinBar           = { fg = p.fg,       bg = p.fill1                                      },
    WinBarNC         = { fg = p.fg,       bg = p.fill1                                      },
    WildMenu         = { fg = p.fill2,       bg = p.cyan                                          },
    Search           = { fg = p.cyan,       bg = p.bg,      reverse = true                  },
    IncSearch        = { fg = p.fgLight,       bg = p.select,     underline = true                },
    CurSearch        = { fg = p.fgLight,       bg = p.select,     underline = true                },
    Substitute       = { fg = p.fgLight,       bg = p.bg,      reverse = true                  },
    TabLine          = { fg = p.fg,       bg = p.fill2                                          },
    TabLineSel       = { fg = p.fg,       bg = p.fill5                                     },
    TabLineFill      = { fg = p.fgDim,   bg = p.fill3                                          },
    Title            = { fg = p.fg,       bg = p.none                                           },
    WinSeparator     = { fg = p.fill2,       bg = p.bgDim                                      },
    VertSplit        = { link = "WinSeparator"                                                     },
    QuickFixLine     = { fg = p.bg,       bg = p.cyan                                          },
    DiffText         = {                     underdashed = true, sp = p.yellowDim                                    },
    DiffAdd          = {                     bg = p.greenDim                                     },
    DiffChange       = {                     bg = p.yellowDim                                     },
    DiffDelete       = {                    bg = p.redDim                                     },
    diffAdded        = { link = "DiffAdd"                                                          },
    diffChanged      = { link = "DiffChange"                                                       },
    diffRemoved      = { link = "DiffDelete"                                                       },
    Yank             = { fg = p.fgLight,       bg = p.select                                         },
}

M.syntax = {
    Comment        = { fg = p.fill5,                                       },

    Constant       = { fg = p.fgLight                                             },
    String         = { fg = p.green,                  italic = true         },
    Character      = { fg = p.green                                            },
    Number         = { fg = p.magenta                                            },
    Boolean        = { fg = p.blue,                   bold = true           },
    Float          = { fg = p.magenta                                            },

    Identifier     = { fg = p.fg,                   },
    Function       = { fg = p.cyan,                   italic = true         },

    Statement      = { fg = p.blue                                             },
    Conditional    = { fg = p.blue,                   italic = true         },
    Repeat         = { fg = p.blue                                             },
    Label          = { fg = p.blue                                             },
    Operator       = { fg = p.blue,                   },
    Keyword        = { fg = p.blue,                   italic = true         },
    Exception      = { fg = p.blue                                             },

    PreProc        = { fg = p.blue,                   },
    Include        = { fg = p.blue                                             },
    Define         = { fg = p.blue                                             },
    Macro          = { link = "Define"                                          },
    PreCondit      = { link = "PreProc"                                         },

    Type           = { fg = p.blue,                   },
    StorageClass   = { fg = p.blue                                             },
    Structure      = { fg = p.blue                                             },
    Typedef        = { fg = p.blue                                             },

    Special        = { fg = p.fg                                             },
    SpecialChar    = { fg = p.yellow                                            },
    Tag            = { fg = p.fg                                             },
    Delimiter      = { fg = p.fgLight                                             },
    SpecialComment = { fg = p.cyan,                   italic = true         },
    Debug          = { fg = p.red                                            },

    Underlined     = { fg = p.green,                  underline = true      },
    Ignore         = { fg = p.fill2                                             },
    Error          = { fg = p.red,     bg = p.none, bold = true, underline = true },
    Todo           = { fg = p.yellow,     bg = p.none                           },
}

M.lsp = {
    -- DocumentHighlight
    LspReferenceText            = { fg = p.none,   bg = p.fill4                                     },
    LspReferenceRead            = { fg = p.none,   bg = p.fill4                                     },
    LspReferenceWrite           = { fg = p.none,   bg = p.fill4                                     },
    -- Neovim LspSignatureHelp
    LspSignatureActiveParameter = { link = "Search"                                                 },
    -- lspinfo window
    LspInfoBorder               = { link = "FloatBorder"                                            },
}
M.diagnostic = {
    DiagnosticError             = { fg = p.red },
    DiagnosticWarn              = { fg = p.yellow },
    DiagnosticInfo              = { fg = p.cyan },
    DiagnosticHint              = { fg = p.select },
    DiagnosticSignError         = { link = "DiagnosticError"                                        },
    DiagnosticSignWarn          = { link = "DiagnosticWarn"                                         },
    DiagnosticSignInfo          = { link = "DiagnosticInfo"                                         },
    DiagnosticSignHint          = { link = "DiagnosticHint"                                         },
    -- DiagnosticDefaultError      = { link = "DiagnosticError"                                        },
    -- DiagnosticDefaultWarn       = { link = "DiagnosticWarn"                                         },
    -- DiagnosticDefaultInfo       = { link = "DiagnosticInfo"                                         },
    -- DiagnosticDefaultHint       = { link = "DiagnosticHint"                                         },
    DiagnosticFloatingWarn      = { link = "DiagnosticError"                                        },
    DiagnosticFloatingError     = { link = "DiagnosticWarn"                                         },
    DiagnosticFloatingInfo      = { link = "DiagnosticInfo"                                         },
    DiagnosticFloatingHint      = { link = "DiagnosticHint"                                         },
    DiagnosticUnderlineError    = {                bg = p.none, underdotted = true,  sp = p.red },
    DiagnosticUnderlineWarn     = {                bg = p.none, underdotted = true,  sp = p.yellow },
    DiagnosticUnderlineInfo     = {                bg = p.none, underdotted = true,  sp = p.cyan  },
    DiagnosticUnderlineHint     = {                bg = p.none, underdotted = true,  sp = p.select },
    DiagnosticVirtualTextError  = { fg = p.red, bg = p.none, bold = true, italic = true               },
    DiagnosticVirtualTextWarn   = { fg = p.yellow, bg = p.none, bold = true, italic = true               },
    DiagnosticVirtualTextInfo   = { fg = p.cyan,  bg = p.none, bold = true, italic = true               },
    DiagnosticVirtualTextHint   = { fg = p.select, bg = p.none, bold = true, italic = true               },
}

M.plugins = {
    -- alpha-nvim
    AlphaButtons         = { fg = p.fg,      bg = p.none },
    AlphaButtonShortcuts = { fg = p.cyan,      bg = p.none },
    AlphaHeader          = { fg = p.blue,      bg = p.none },
    AlphaFooter          = { fg = p.fill5, bg = p.none },

    -- diffview.nvim
    DiffviewVertSplit    = { fg = p.fill2, bg = p.yellow   },
    DiffviewWinSeparator = { link = "DiffviewVertSplit"    },

    -- gitsigns.nvim
    GitSignsCurrentLineBlame = { fg = p.magenta, bold = true, italic = true },
    GitSignsAdd              = { fg = p.green, },
    GitSignsAddNr            = { fg = p.green, bg = p.fill2                              },
    GitSignsAddLn            = {                bg = p.greenDark                       },
    GitSignsChange           = { fg = p.yellow, },
    GitSignsChangeNr         = { fg = p.yellow, bg = p.fill2                              },
    GitSignsChangeLn         = {                bg = p.yellowDark                       },
    GitSignsDelete           = { fg = p.red, },
    GitSignsDeleteNr         = { fg = p.red, bg = p.fill2                              },
    GitSignsDeleteLn         = {                bg = p.redDark                       },
    GitSignsAddInline        = {                bg = p.greenDim                         },
    GitSignsChangeInline     = {                bg = p.yellowDim                         },
    GitSignsDeleteInline     = {                bg = p.redDim                         },

    -- incline.nvim
    InclineNormal   = { fg = p.nord5, bg = p.fill4 },
    InclineNormalNC = { link = "InclineNormal"     },

    -- indent-blankline.nvim
    IndentBlanklineContextChar        = { fg = p.violet, bg = p.none                                    },
    IndentBlanklineContextStart       = { fg = p.none,  bg = p.none, underline = true, sp = p.violet },
    IndentBlanklineSpaceCharBlankline = { fg = p.fill2, bg = p.none                                    },
    IndentBlanklineSpaceChar          = { fg = p.fill2, bg = p.none                                    },
    IndentBlanklineChar               = { fg = p.fill2, bg = p.none                                    },

    -- hop.nvim
    HopNextKey   = { fg = p.cyan, bg = p.none, bold = true },
    HopNextKey1  = { fg = p.cyan, bg = p.none                 },
    HopNextKey2  = { fg = p.fg, bg = p.none                 },
    HopUnmatched = { fg = p.fill4, bg = p.none                 },

    -- mini.nvim
    MiniCursorword        = { link = "Visual" },
    MiniCursorwordCurrent = { bold = true  },

    -- nvim-cmp
    CmpGhostText             = { fg = p.fill5, bold = true          },

    CmpItemMenu              = { fg = p.fill5                                       },

    CmpItemAbbr              = { fg = p.fg                                            },
    CmpItemAbbrDeprecated    = { fg = p.orange,      strikethrough = true },
    CmpItemAbbrMatch         = { fg = p.select,      bold = true          },
    CmpItemAbbrMatchFuzzy    = { link = "CmpItemAbbrMatch"                               },

    CmpItemKind              = { link = "Normal"                                         },
    CmpItemKindTypeParameter = { link = "TSParameter"                                    },
    CmpItemKindConstructor   = { link = "TSConstructor"                                  },
    CmpItemKindEnum          = { link = "Structure"                                    },
    CmpItemKindEnumMember    = { link = "Structure"                                    },
    CmpItemKindReference     = { link = "TSParameterReference"                           },
    CmpItemKindInterface     = { link = "StorageClass"                                   },
    CmpItemKindClass         = { link = "StorageClass"                                   },
    CmpItemKindVariable      = { link = "TSVariable"                                     },
    CmpItemKindProperty      = { link = "TSProperty"                                     },
    CmpItemKindOperator      = { link = "TSOperator"                                     },
    CmpItemKindFunction      = { link = "TSFunction"                                     },
    CmpItemKindConstant      = { link = "TSConstant"                                     },
    CmpItemKindSnippet       = { fg = p.green                                           },
    CmpItemKindKeyword       = { link = "TSKeyword"                                      },
    CmpItemKindStruct        = { link = "Structure"                                    },
    CmpItemKindModule        = { link = "TSNamespace"                                    },
    CmpItemKindMethod        = { link = "TSMethod"                                       },
    CmpItemKindFolder        = { link = "Directory"                                      },
    CmpItemKindFile          = { link = "Directory"                                      },
    CmpItemKindValue         = { link = "TSKeyword"                                      },
    CmpItemKindField         = { link = "TSField"                                        },
    CmpItemKindUnit          = { link = "TSNumber"                                       },
    CmpItemKindText          = { link = "TSText"                                         },

    -- nvim-hlslens
    HlSearchNear     = { link = "IncSearch"                                },
    HlSearchLensNear = { fg = p.fg,      bg = p.none, reverse = true },
    HlSearchLens     = { fg = p.fill5, bg = p.none, reverse = true },
    HlSearchFloat    = { link = "IncSearch"                                },

    -- nvim-notify
    NotifyERRORTitle  = { fg = p.red, bg = p.bgDark },
    NotifyWARNTitle   = { fg = p.yellow, bg = p.bgDark },
    NotifyINFOTitle   = { fg = p.cyan,  bg = p.bgDark },
    NotifyDEBUGTitle  = { fg = p.orange, bg = p.bgDark },
    NotifyTRACETitle  = { fg = p.select, bg = p.bgDark },
    NotifyERRORIcon   = { fg = p.red, bg = p.bgDark },
    NotifyWARNIcon    = { fg = p.yellow, bg = p.bgDark },
    NotifyINFOIcon    = { fg = p.cyan,  bg = p.bgDark },
    NotifyDEBUGIcon   = { fg = p.orange, bg = p.bgDark },
    NotifyTRACEIcon   = { fg = p.select, bg = p.bgDark },
    NotifyERRORBorder = { link = "FloatBorder"              },
    NotifyWARNBorder  = { link = "FloatBorder"              },
    NotifyINFOBorder  = { link = "FloatBorder"              },
    NotifyDEBUGBorder = { link = "FloatBorder"              },
    NotifyTRACEBorder = { link = "FloatBorder"              },
    NotifyERRORBody   = { link = "NormalFloat"              },
    NotifyWARNBody    = { link = "NormalFloat"              },
    NotifyINFOBody    = { link = "NormalFloat"              },
    NotifyDEBUGBody   = { link = "NormalFloat"              },
    NotifyTRACEBody   = { link = "NormalFloat"              },

    -- nvim-scrollbar
    ScrollBarHandle = { fg = p.none,  bg = p.fill3 },
    ScrollBarError  = { link = "DiagnosticError"   },
    ScrollBarWarn   = { link = "DiagnosticWarn"    },
    ScrollBarInfo   = { link = "DiagnosticInfo"    },
    ScrollBarHint   = { link = "DiagnosticHint"    },
    ScrollBarMisc   = { fg = p.fg, bg = p.none  },
    ScrollBarSearch = { link = "Search"            },

    -- nvim-ts-rainbow
    rainbowcol1 = { fg = p.select, bg = p.none },
    rainbowcol2 = { fg = p.red, bg = p.none },
    rainbowcol3 = { fg = p.yellow, bg = p.none },
    rainbowcol4 = { fg = p.green, bg = p.none },
    rainbowcol5 = { fg = p.magenta, bg = p.none },
    rainbowcol6 = { fg = p.violet,  bg = p.none },
    rainbowcol7 = { fg = p.fg,  bg = p.none },

    --nvim-windowpicker
    WindowPicker   = { fg = p.bgDark, bg = p.select, bold = true },
    WindowPickerNC = { fg = p.bgDark, bg = p.select, bold = true },

    -- neo-tree.nvim
    NeoTreeNormal               = { link = "Normal"                                                  },
    NeoTreeNormalNC             = { link = "NormalNC"                                                },
    NeoTreePreview              = { fg    = p.fg,         bg = p.fill5                       },
    NeoTreeFloatBorder          = { fg    = p.fill3,         bg = p.bg                            },
    NeoTreeFloatTitle           = { fg    = p.cyan,         bg = p.fill3,     bold = true        },

    NeoTreeTabActive            = { fg    = p.fg,         bg = p.fill5                       },
    NeoTreeTabInactive          = { fg    = p.fg,         bg = p.fill3                            },
    NeoTreeTabBarBackground     = { link = "StatusLine"                                              },
    NeoTreeTabSeparatorActive   = { fg    = p.fill4,         bg = p.fill5                       },
    NeoTreeTabSeparatorInactive = { fg    = p.fill2,         bg = p.fill3                            },

    NeoTreeRootName             = { fg    = p.fgLight,         bg = p.none,      bold = true, italic = true },
    NeoTreeIndentMarker         = { link = "FoldColumn"                                              },
    NeoTreeFileNameOpened       = { bold = true, nocombine = true                                         },
    NeoTreeBufferNumber         = { fg    = p.fgLight,         bg = p.none                             },
    NeoTreeDotfile              = { fg    = p.fill5,    bg = p.none                             },
    NeoTreeSymbolicLinkTarget   = { fg    = p.violet,         bg = p.none,      bold = true        },

    NeoTreeMessage              = { fg    = p.magenta,        bg = p.none                             },
    NeoTreeDimText              = { fg    = p.fill4,         bg = p.none                             },
    NeoTreeFadeText1            = { link = "NeoTreeDotfile"                                          },
    NeoTreeFadeText2            = { link = "NeoTreeDimText"                                          },

    NeoTreeModified             = { link = "GitSignsChange"                                          },
    NeoTreeGitAdded             = { link = "GitSignsAdd"                                             },
    NeoTreeGitModified          = { link = "GitSignsChange"                                          },
    NeoTreeGitDeleted           = { link = "GitSignsDelete"                                          },
    NeoTreeGitRenamed           = { link = "NeoTreeGitModified"                                      },
    NeoTreeGitUntracked         = { fg    = p.select,        bg = p.none                             },
    NeoTreeGitIgnored           = { link = "NeoTreeDotfile"                                          },
    NeoTreeGitUnstaged          = { link = "NeoTreeGitModified"                                      },
    NeoTreeGitStaged            = { link = "NeoTreeGitAdded"                                         },
    NeoTreeGitConflict          = { fg    = p.orange,        bg = p.none                             },

    -- quickscope.lua
    QuickScopePrimary   = { fg = p.yellow, bg = p.bg, underline = true, nocombine = true },
    QuickScopeSecondary = { fg = p.magenta, bg = p.bg, bold = true, nocombine = true      },

    -- satellite.nvim
    ScrollView = { fg = p.none,  bg = p.fill4 },
    SearchSV   = { fg = p.cyan, bg = p.none  },

    -- telescope.nvim
    TelescopePromptPrefix   = { fg = p.fg, bg = p.none,       bold = true },
    TelescopePromptCounter  = { fg = p.violet, bg = p.none,       bold = true },

    TelescopeNormal         = { fg = p.fg, bg = p.bgDark                },
    TelescopeResultsNormal  = { fg = p.blue, bg = p.none                       },
    TelescopePreviewNormal  = { fg = p.fg, bg = p.bg                      },
    TelescopePromptNormal   = { fg = p.fgLight, bg = p.bg                      },

    TelescopeResultsTitle   = { fg = p.cyan, bg = p.fill3,      bold = true },
    TelescopePreviewTitle   = { fg = p.blue, bg = p.fill3,      bold = true },
    TelescopePromptTitle    = { fg = p.fg, bg = p.fill3,      bold = true },

    TelescopeResultsBorder  = { fg = p.fill3, bg = p.none                       },
    TelescopePreviewBorder  = { fg = p.fill3, bg = p.bg                      },
    TelescopePromptBorder   = { fg = p.fill3, bg = p.bg                      },

    TelescopeMultiSelection = { fg = p.fgLight, bg = p.fill3                      },
    TelescopeMultiIcon      = { fg = p.fgLight, bg = p.fill3                      },
    TelescopeSelectionCaret = { fg = p.cyan, bg = p.fill2                      },
    TelescopeSelection      = { link = "TelescopeSelectionCaret"                },
    TelescopeMatching       = { fg = p.fgLight, bg = p.none                       },

    -- todo-comments.nvim
    TodoBgFIX    = { fg = p.fgLight,  bg = p.red, bold = true },
    TodoFgFIX    = { link = "DiagnosticError"                     },
    TodoSignFIX  = { link = "DiagnosticError"                     },
    TodoBgNOTE   = { fg = p.fgLight,  bg = p.select, bold = true },
    TodoFgNOTE   = { link = "DiagnosticHint"                      },
    TodoSignNOTE = { link = "DiagnosticHint"                      },
    TodoBgWARN   = { fg = p.fgLight,  bg = p.yellow, bold = true },
    TodoFgWARN   = { link = "DiagnosticWarn"                      },
    TodoSignWARN = { link = "DiagnosticWarn"                      },
    TodoBgPERF   = { fg = p.fgLight,  bg = p.green, bold = true },
    TodoFgPERF   = { fg = p.green, bg = p.none                   },
    TodoSignPERF = { fg = p.green, bg = p.none                   },
    TodoBgTODO   = { fg = p.fgLight,  bg = p.cyan,  bold = true },
    TodoFgTODO   = { link = "DiagnosticInfo"                      },
    TodoSignTODO = { link = "DiagnosticInfo"                      },
    TodoBgHACK   = { fg = p.fgLight,  bg = p.yellow, bold = true },
    TodoFgHACK   = { link = "DiagnosticWarn"                      },
    TodoSignHACK = { link = "DiagnosticWarn"                      },

    -- vim-illuminate
    IlluminatedWordText  = { link = "Visual" },
    IlluminatedWordRead  = { link = "Visual" },
    IlluminatedWordWrite = { link = "Visual" },

    -- which-key.nvim
    WhichKey          = { fg = p.fg,  bg = p.none, bold = true },
    WhichKeyBorder    = { link = "FloatBorder" },
    WhichKeyGroup     = { fg = p.select, bg = p.none, bold = true },
    WhichKeyDesc      = { fg = p.blue,  bg = p.none                 },
    WhichKeySeparator = { fg = p.fill4,  bg = p.none                 },
    WhichKeyValue     = { link = "Comment"                           },
    WhichKeyFloat     = { link = "NormalFloat"                       },

    -- hydra.nvim
    HydraHint     = { link = "NormalFloat"       },
    HydraAmaranth = { fg = p.orange, bg = p.none },
    HydraTeal     = { fg = p.violet,  bg = p.none },
    HydraPink     = { fg = p.magenta, bg = p.none },
    HydraBlue     = { fg = p.select, bg = p.none },
    HydraRed      = { fg = p.red, bg = p.none }
}

M.statusBars = {
    ModeInactive                  = { fg = p.fill2,     bg = p.cyan                   },
    ModeVisual                    = { fg = p.fill2,     bg = p.yellow                  },
    ModeReplace                   = { fg = p.fill2,     bg = p.red                  },
    ModeNormal                    = { fg = p.fill2,     bg = p.cyan                   },
    ModeInsert                    = { fg = p.fill2,     bg = p.fgLight                   },
    ModeCommand                   = { fg = p.fill2,     bg = p.violet                   },
    ModeTerminal                  = { fg = p.fill2,     bg = p.orange                  },
    ModeHydra                     = { fg = p.fill2,     bg = p.magenta                  },
    StatusLineLight               = { fg = p.fg,     bg = p.fill4                   },
    WinBarLight                   = { fg = p.fg,     bg = p.fill3                   },
    WinBarCurrent                 = { fg = p.fgLight,     bg = p.fill5              },
    WinBarSpecial                 = { fg = p.fg,     bg = p.fill1,  bold = true },
    WinBarCurrentSpecial          = { fg = p.fgLight,     bg = p.fill5, bold = true },
    WinBarModifiedCurrent         = { fg = p.fill1, bg = p.yellow                  },
    WinBarModifiedInactive        = { fg = p.yellow,    bg = p.fill1               },
    WinBarWindowNumber            = { fg = p.fgLight                                     },
    TabLine                       = { fg = p.fg,     bg = p.fill2                   },
    TabLineSel                    = { fg = p.fg,     bg = p.fill5              },
    TabLineFill                   = { fg = p.fgDim, bg = p.fill3                   },
    TabLineHeader                 = { fg = p.fill2,     bg = p.cyan                   },
    TabLineTabSeparator           = { fg = p.fg,     bg = p.fill4                   },
    TabLineTabSeparatorSel        = { fg = p.fill2,     bg = p.cyan                   },
    TabLineTabIndicator           = { fg = p.fg,     bg = p.fill4                   },
    TabLineTabIndicatorSel        = { fg = p.fill2,     bg = p.cyan                   },
    TabLineIndicatorModified      = { fg = p.fill2,     bg = p.fill3                   },
    TabLineIndicatorModifiedSel   = { fg = p.fill2,     bg = p.fill5              },
    TabLineIndicatorIsModified    = { fg = p.yellow,    bg = p.fill3                   },
    TabLineIndicatorIsModifiedSel = { fg = p.yellow,    bg = p.fill5              },
}

M.treesitter = {
    TSComment            = { link = "Comment"                                  },
    TSConstant           = { link = "Constant"                                 },
    TSConstBuiltin       = { link = "Constant"                                 },
    TSConstMacro         = { link = "Constant"                                 },
    TSField              = { fg = p.fg                                },
    TSString             = { link = "String"                                   },
    TSStringRegex        = { link = "SpecialChar"                              },
    TSStringEscape       = { fg = p.magenta                               },
    TSStringSpecial      = { link = "Special"                                  },
    TSCharacter          = { link = "Character"                                },
    TSCharacterSpecial   = { link = "Special"                                  },
    TSText               = { fg = p.fg                                },
    TSTextReference      = { fg = p.magenta                               },
    TSLiteral            = { fg = p.fg                                },
    TSNumber             = { link = "Number"                                   },
    TSBoolean            = { link = "Boolean"                                  },
    TSFloat              = { link = "Float"                                    },
    TSNamespace          = { fg = p.fg,  italic = true                },
    TSVariable           = { link = "Identifier"                               },
    TSVariableBuiltin    = { link = "Keyword"                                  },
    TSFunction           = { link = "Function"                                 },
    TSFuncBuiltin        = { link = "Function"                                 },
    TSFuncMacro          = { link = "Function"                                 },
    TSConditional        = { link = "Conditional"                              },
    TSRepeat             = { link = "Repeat"                                   },
    TSLabel              = { link = "Label"                                    },
    TSOperator           = { link = "Operator"                                 },
    TSKeyword            = { link = "Keyword"                                  },
    TSKeywordFunction    = { link = "Keyword"                                  },
    TSKeywordReturn      = { link = "Keyword"                                  },
    TSKeywordOperator    = { link = "Keyword"                                  },
    TSException          = { link = "Exception"                                },
    TSInclude            = { fg = p.blue                                },
    TSMethod             = { fg = p.violet,  italic = true                },
    TSConstructor        = { fg = p.blue                                },
    TSProperty           = { fg = p.select, italic = true                },
    TSType               = { link = "Type"                                     },
    TSTypeBuiltin        = { link = "Type"                                     },
    TSStructure          = { link = "Structure" },
    TSPunctDelimiter     = { fg = p.cyan },
    TSPunctBracket       = { fg = p.cyan },
    TSPunctSpecial       = { fg = p.cyan },
    TSTag                = { link = "Tag" },
    TSTagAttribute       = { link = "TSTag" },
    TSTagDelimiter       = { link = "TSTag" },
    TSAnnotation         = { link = "Annotation" },
    TSEmphasis           = { italic = true },
    TSStrong             = { bold = true },
    TSUnderline          = { underline = true },
    TSStrike             = { strikethrough = true },
    -- TSError              = { link = "Error" },
    TSAttribute          = { fg = p.magenta },
    TSParameter          = { fg = p.select },
    TSParameterReference = { fg = p.select },
    TSSymbol             = { fg = p.magenta },
    TSTitle              = { fg = p.blue, bold = true },
    TSURI                = { fg = p.select },
    TSDebug              = { link = "Debug" },
    TSDefine             = { link = "Define" },
    -- TSNone = { },
    TSPreProc            = { link = "PreProc" },
    TSStorageClass       = { link = "StorageClass" },
    TSMath               = { link = "Number" },
    -- TSEnvironment = { },
    -- TSEnvironmentName = { },
    TSNote               = { link = "DiagnosticHint" },
    TSWarning            = { link = "DiagnosticWarn" },
    TSDanger             = { link = "DiagnosticError" },
}

return M
